### ISSUE TITLE
Found but...

### ISSUE THREAD

**Issue by dgoyo** [hybula/whmcs-turnstile#6]
I add the const lines on the top of hook file.
The script not fond:

Oops!
Something went wrong and we couldn't process your request.

Please go back to the previous page and try again.

Php: 8.1
WHMCS: Version: 8.10.1

Update............

I added the lines to the end of the hook and it worked perfectly.

**Comment by dqos** [comment]
Without error logs we can't investigate, you can place the consts in your configuration.php. Closing this.
