### ISSUE TITLE
const variables correct line placement

### ISSUE THREAD

**Issue by trinib** [hybula/whmcs-turnstile#7]
hey thanks for this btw. Only issue I was getting was adding :
```const hybulaTurnstileEnabled = true;
const hybulaTurnstileCredits = true;
const hybulaTurnstileExcludeLogin = true;
const hybulaTurnstileSite = '';
const hybulaTurnstileSecret = '';
const hybulaTurnstileTheme = 'auto';
const hybulaTurnstileError = 'Something went wrong with your captcha challenge!';
const hybulaTurnstileLocations = ['login', 'register', 'checkout', 'ticket', 'contact'];
```
adding it to first or last lines in hook file results in error, adding it after :
```
declare(strict_types=1);

if (!defined('WHMCS')) {
    die('This file cannot be accessed directly!');
}
```
works perfectly👍

Also you stated in readme to add hook file in root whmcs folder which did not work, addling it to **/includes/hooks/** did worked ! Create one file with all code is easier. No need to add variables in configuration file.

**Comment by BNBox** [comment]
Totally agreed.
I was facing the same problem and got it fixed by adding the code after the section mentioned here.

I also don't understand why not having the hybula_turnstile.php 100% ready with the parameters code all inserted by default. There is no need to add anything in configuration.php file.

So far, so good.

**Comment by dqos** [comment]
@trinib the hook file should be placed in `includes/hooks` like it's done in this repository. If you unzip this in your root, it will be placed in this directory.

@BNBox it's completely sane to place the configuration constants in `configuration.php`, so you have one place to manage your settings and you can then easily upgrade this hook in the future without overwriting the config.

I will try to make it even more clearer in the README.
